### ISSUE TITLE
[TASK]: Flesh out `compose` API proposal

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/model-transform#3]
**Describe the task**
Create a `compose` API endpoint that will then be presented to TA2.

**Comment by bencodrington** [comment]
We proposed the initial version to TA2, didn't get much feedback.
For now, we'll proceed with [stubbing the endpoint](https://github.com/DARPA-ASKEM/model-transform/issues/10) and reconsult TA2 at that point before [fleshing out the stubbed endpoint](https://github.com/DARPA-ASKEM/model-transform/issues/11).
